[project]
name = "gallifrey"
version = "0.1.1"
description = "A JAX-based gaussian process structure learning package for time series modelling."
authors = [
    {name = "Chris Boettner",email = "boettnec@gmail.com"}
]
license = {text = "Apache 2.0"}
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "blackjax (>=1.5)",
    "jax (>=0.9.2)",
    "flax (>=0.12.6)",
    "equinox (>=0.13.6)",
    "beartype (>=0.19.0,<0.20.0)",
    "tfp-nightly (>=0.26.0.dev20260406)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
